FROM node:8-alpine

WORKDIR /usr/app/

COPY package*.json ./
RUN npm install

ENV TCP_PORT 5000
ENV UDP_PORT 6000
ENV DEBUG backend-location-tracker:*

CMD ["./node_modules/nodemon/bin/nodemon.js", "./lib/backend/index.js"]